import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import { Layout } from "@vassembly/ui-layout";
import "./globals.scss";
import { Providers } from "./providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-family-body",
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-family-display",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${spaceGrotesk.variable}`}
    >
      <body className={inter.className}>
        <Providers>
          <Layout variant="main">{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
