import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import {
  SocialFacebookColorIcon,
  SocialInstagramColorIcon,
  SocialTwitterColorIcon,
} from "@vassembly/ui-icons";
import { Footer } from "../../../ui/footer/src";
import { LayoutContent } from "./LayoutContent";
import "./globals.scss";
import layoutStyles from "./layout.module.scss";
import { Providers } from "./providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-family-body",
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-family-display",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${spaceGrotesk.variable}`}
    >
      <body className={inter.className}>
        <Providers>
          <LayoutContent>
            <div className={layoutStyles.page}>
              <main id="main-content" className={layoutStyles.main}>
                {children}
              </main>
              <Footer
                sitemap={[
                  { label: "Home", href: "/" },
                  { label: "Docs", href: "/docs" },
                ]}
                company={[{ label: "About us", href: "/about" }]}
                legal={[
                  { label: "Privacy", href: "/privacy" },
                  { label: "Terms & conditions", href: "/terms" },
                ]}
                contact={{
                  email: {
                    label: "Email",
                    value: "hello@vassembly.dev",
                    href: "mailto:hello@vassembly.dev",
                  },
                }}
                social={[
                  {
                    href: "https://twitter.com",
                    ariaLabel: "X",
                    icon: <SocialTwitterColorIcon />,
                  },
                  {
                    href: "https://facebook.com",
                    ariaLabel: "Facebook",
                    icon: <SocialFacebookColorIcon />,
                  },
                  {
                    href: "https://instagram.com",
                    ariaLabel: "Instagram",
                    icon: <SocialInstagramColorIcon />,
                  },
                ]}
                copyright="© 2026 Vassembly. All rights reserved."
              />
            </div>
          </LayoutContent>
        </Providers>
      </body>
    </html>
  );
}
