export enum MCP_SLUG {
  ArxivMcp = 'arxiv-mcp',
  AwsMcp = 'aws-mcp',
  BraveSearchMcp = 'brave-search-mcp',
  CanvaMcp = 'canva-mcp',
  Context7 = 'context7',
  DatadogMcp = 'datadog-mcp',
  DiscordMcp = 'discord-mcp',
  FigmaMcp = 'figma-mcp',
  GithubMcp = 'github-mcp',
  GmailMcp = 'gmail-mcp',
  GoogleCalendarMcp = 'google-calendar-mcp',
  GoogleMapsMcp = 'google-maps-mcp',
  GoogleSearchMcp = 'google-search-mcp',
  GoogleSheetsMcp = 'google-sheets-mcp',
  GranolaMcp = 'granola-mcp',
  LinearMcp = 'linear-mcp',
  MongodbMcp = 'mongodb-mcp',
  NotionMcp = 'notion-mcp',
  ObsidianMcp = 'obsidian-mcp',
  OpenweatherMcp = 'openweather-mcp',
  PubmedMcp = 'pubmed-mcp',
  RedisMcp = 'redis-mcp',
  SentryMcp = 'sentry-mcp',
  SpotifyMcp = 'spotify-mcp',
  StripeMcp = 'stripe-mcp',
  TerraformMcp = 'terraform-mcp',
  TodoistMcp = 'todoist-mcp',
  VercelMcp = 'vercel-mcp',
  WikipediaMcp = 'wikipedia-mcp',
}

export const getMcpSlugs = (): MCP_SLUG[] => Object.values(MCP_SLUG);
