export enum SYSTEM_AGENT_NAME {
  Assistant = 'Assistant',
  IntentClassifier = 'Intent classifier',
  QuestionWorker = 'Question worker',
  TaskWorker = 'Task worker',
  ScheduledTaskWorker = 'Scheduled task worker',
  RoutineTaskWorker = 'Routine task worker',
  TaskTitleGenerator = 'Task title generator',
  SpecializationClassifier = 'Specialization classifier',
  McpSpecializationClassifier = 'MCP specialization classifier',
  SpecializationAgentDescriptionGenerator = 'Specialization agent description generator',
  SkillResolver = 'Skill resolver',
  TaskPlanner = 'Task planner',
  SkillPlanner = 'Skill planner',
  SkillScriptCreatorPython = 'Skill script creator (python)',
  SkillScriptCreatorJavascript = 'Skill script creator (javascript)',
  SkillScriptCreatorBash = 'Skill script creator (bash)',
}
