import React from "react";
import { IconProps } from "./types";

export const ReorderDownIcon = ({ className, style }: IconProps) => (
  <svg
    style={style}
    className={className}
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    strokeWidth="1.5px"
  >
    <defs></defs>
    <title>reorder-down</title>
    <line
      x1="18.75"
      y1="20.25"
      x2="18.75"
      y2="3.75"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></line>
    <path
      d="M14.25,15.75l3.97,4.28a.749.749,0,0,0,1.06,0l3.97-4.28"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></path>
    <rect
      x="0.75"
      y="0.75"
      width="9"
      height="9"
      rx="1"
      ry="1"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></rect>
    <path
      d="M2.25,23.25a1.5,1.5,0,0,1-1.5-1.5"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></path>
    <path
      d="M.75,15.75a1.5,1.5,0,0,1,1.5-1.5"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></path>
    <path
      d="M8.25,23.25a1.5,1.5,0,0,0,1.5-1.5"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></path>
    <path
      d="M9.75,15.75a1.5,1.5,0,0,0-1.5-1.5"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></path>
    <line
      x1="4.5"
      y1="23.25"
      x2="6"
      y2="23.25"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></line>
    <line
      x1="4.5"
      y1="14.25"
      x2="6"
      y2="14.25"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></line>
    <line
      x1="0.75"
      y1="18"
      x2="0.75"
      y2="19.5"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></line>
    <line
      x1="9.75"
      y1="18"
      x2="9.75"
      y2="19.5"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></line>
  </svg>
);
