declare const styles: {
  readonly root: string;
  readonly column: string;
  readonly grid: string;
  readonly slotBrand: string;
  readonly slotSitemap: string;
  readonly slotCompanyLegal: string;
  readonly slotContactSocial: string;
  readonly slotCopyright: string;
  readonly columnTitle: string;
  readonly linkList: string;
  readonly linkListItem: string;
  readonly footerLink: string;
  readonly companyLegalInner: string;
  readonly legalGap: string;
  readonly contactInner: string;
  readonly contactRow: string;
  readonly contactLabel: string;
  readonly contactValue: string;
  readonly contactSocialInner: string;
  readonly socialRow: string;
  readonly socialItem: string;
  readonly socialLink: string;
  readonly socialIcon: string;
  readonly brandBlock: string;
  readonly copyright: string;
};
export default styles;
