import React from "react";
import { IconProps } from "./types";

export const BasilicaVaticanIcon = ({ className, style }: IconProps) => (
  <svg
    style={style}
    className={className}
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 24 24"
    strokeWidth="1.5px"
  >
    <defs></defs>
    <title>basilica -vatican</title>
    <rect
      x="18"
      y="13"
      width="5"
      height="10"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></rect>
    <rect
      x="1"
      y="13"
      width="5"
      height="10"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></rect>
    <polygon
      points="12 11 6 13 6 23 18 23 18 13 12 11"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></polygon>
    <line
      x1="8.79"
      y1="14.976"
      x2="15.21"
      y2="14.976"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></line>
    <line
      x1="9.505"
      y1="23"
      x2="9.505"
      y2="14.976"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></line>
    <line
      x1="14.495"
      y1="23"
      x2="14.495"
      y2="14.976"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></line>
    <path
      d="M6,12.25a2.5,2.5,0,0,0-5,0V13H6Z"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></path>
    <path
      d="M23,12.25a2.5,2.5,0,0,0-5,0V13h5Z"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></path>
    <polyline
      points="8 9.5 8 8 16 8 16 9.5"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></polyline>
    <path
      d="M8,8a4,4,0,0,1,8,0"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></path>
    <line
      x1="12"
      y1="3.5"
      x2="12"
      y2="1"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></line>
    <line
      x1="11"
      y1="2"
      x2="13"
      y2="2"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
    ></line>
  </svg>
);
